language: java
install: mvn install -DskipTests=true -Dgpg.skip=true -Djavadoc.skip=true
script: mvn package -DskipTests=true -Dgpg.skip=true -Djavadoc.skip=true
env:
  global:
  - SONATYPE_USERNAME=onesuperclark
  - secure: jotelfD8Vdo7IWjU5ToEDk6PY/Ccdbf/phuRxk/v90rCPfkJ5lxFnY81anLocvQUSynLC+erIEzPPSYbq2NVv4x91snNL7qmzHnU57gTrXbYQiiIupHSoGDJHmIF22lApDmMWU2yayoG8YLUuWE13aQpxD2s3H/EwM6KuJMd48eNW18cWukj3M5uqABDvzGL+U8YIQP9Y4EhYLixqwAXHpnJQgqaTQ4B6mBQrHv60bIwep48K5iOPuAnznhNkRIbHKQzkxio2OCx/x6In8Dm6cgje9mHypcsYn2SyQ63D5KWWPFQhToUGSMLbjXUJJ+uYB1ZxnglhjbutaZ1/5Rd15fS/QpXyMGLK8OB8cnBxaQYhWmV2bAq837D0EQ2XCc7hRg9o7y8U6T0VzQ8hrGAXRKrXwfKHI12ymExRNWirCNHs7VFHV8Dd1CieMUrOvVm/KNEb7FQW+9NVYns4fEtJCQtcGCIEsERpIBPbQXXRAdJWmh9SniCQZaaCEhBCF8zXOYYBAPLQ1VeyBVUgKiJk7JUby4hV+RHe9f3dGDiy4NsS9ghR+YDwPhPZMgvcOH0jsPKLhFhnEAdex9JMKn1NVPAacKCpK5eselGRfm0BpKEgrZR0YVsfGdDSrSCDJG98Zq8112cdYVen3f8W+sSE8G5qInVleo4QVVheDjwKdw=
  - secure: mXiTTXbzP5Li+CN+6q4GgCIZvJbD1BF5563WSZIQytDAXnFY7p6RjLJievG8PhOxtVgjFy1tTHxSXSmF3n5zsBw5ydpkMh8/emBgqPTLuW0HgQ9rRGtQGno0ZYEDTSbLE/HxgyWpIuJ8FT9qQ2gCq6xRjNrGOBf2FwnohhCBMnQngeIOjenHNxMv19WlIzhVJfgjkRc01KGFEmytmF9+2oYH78Zf5ahj8SYJLsM13+Dtbgt34Lzc1ioxkegnnw4PpRp2cOZqisfHINl8K++OGdGYx79X9WCdga4lQLIpFg4HSrBBUp+ZB6qMa/O2hmclz8LoCx7h0ZPEPN3eiRPeZ3VR/JwnWMHqJnR77jljhV6DQ43ruWqpJu/1MZfW1F7Wlzz+UaRjcO6ATXDGRQB7bV+prMYTo8GnW9gZzgJ0G5zem422cL8yQgcwox+2fmVn0lH0k2jEJ9NYcWs/qGCyvkU7hZb4S8FJfFIeoA/tr9Hy4fLUQCWdQcF0Uh4tuvC/AaXkSv8Q/AmruoO4F3IB3+r9zkwG/q7Ah18GZamBrcGig9+xi+V54CJQWeAtpx9uCcW09BRmHBzJ7FxikIaQ816dn88BEO/vDXpVZDJYYocKiVFx9fo7dP7aZLAdkTEOjq6rmls98HGoxpkLaHOJztfj5mXs5l4Lpv1y3Lel114=
before_install:
- openssl aes-256-cbc -K $encrypted_7f0de2c50f2d_key -iv $encrypted_7f0de2c50f2d_iv
  -in secret.key.asc.enc -out secret.key.asc -d
before_deploy:
- export RELEASE_JARS=$(ls target/odps-jdbc-*.jar)
- echo "deploying RELEASE_JARS to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: oWaepWSnXvmwaYJx6lVodPE0LsFSBxTqy68dtRpv+F8N2MAVtODT0UE15OpgyfIKNZc+YvTSP5Y1/dGjBbmSL+O1tLR3BDOumNfODYJ4a5bflcGWueyJd0UvaI5fkpRnNe90ATqtG0cvrPfVhDsP64DRRZcqXMaX/pmU0N33j6F8yjQKeDjemKhgx927k62SpOM01Rnk28MXH9oicpgO9WxqwRQ5MzoYjuGMppCswkIuTQDfAUbRJdqUvblZWrctkdIiteB6WmjCDmnYLz4m6c/ORHJHmXJhli9M7YoOE3GIfRkzNGlz1TSsNGRRJDu+gR2ZYPgoVit/o0JLB7WNMFuhHc5HXO81LYmJnqiauRbj47aDVCbhoP0SBFGZRPgaYotmfVfhLcGCmYDFy6E0/E4SJ0PfZOkxo2JOf538Ik61H79ouKKr4n3M5/7L2AnlMX+Sf98jzDpQ4Iv7LCcu/dfFra7+skmeuVC6bHlV3AHogqVcX+2qy7YcktT84RkEYPjEP81BOaER5Tk8wGG8SGiGRVnY442/Y7j35SE+idOIy2RZjFOstPt8QHjBEQ9ZwpIbAkQsa0RK4SQ2Qd3/+x0umMOifeKAbxWH21cz8ge8wYpWZkCOZda734ECkNK5TvqX/yen0blGrjUMhQ38HlN7Hhb1yexYChBkVrvRiV0=
  file_glob: true
  file: target/odps-jdbc-*.jar
  skip_cleanup: true
  on:
    tags: true
after_deploy:
- echo "deploying to maven central"
- gpg --import secret.key.asc
- mvn deploy --settings settings.xml -DskipTests=true -Dgpg.passphrase=$GPG_PASSPHRASE
